import { StyleSheet } from 'react-native';
import scaleStyle from '@/utils/scaleStyle';

const style = {
  title: {
    // color: '$BlackS',
    color: '$White',
    fontSize: 32,
    fontWeight: '$Medium',
  },
  tipsHeaderBtn: {
    marginRight: 10,
    backgroundColor: '#fedc5b',
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderColor: '#D9B52D',
    borderWidth: 1,
  },
  setting: {
    width: 36,
    height: 32,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 200,
    borderWidth: 3,
    borderColor: '$White',
  },
  name: {
    fontSize: 32,
    color: '$BlackS',
    fontWeight: '$Medium',
    marginRight: 14,
  },
  content: {
    fontSize: '$FontSizeS',
    color: '$White',
  },
  copyBt: {
    borderRadius: 15,
    backgroundColor: '#ffd988',
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginLeft: 9,
  },
  copyBtText: {
    fontSize: 20,
    color: '#FF8B0F',
  },
  guidePanel: {
    flex: 1,
    marginHorizontal: 24,
    paddingHorizontal: 50,
    paddingTop: 23,
    paddingBottom: 39,
    borderRadius: 20,
    backgroundColor: '$White',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  guideInfo: {
    flex: 1,
    marginHorizontal: 24,
    marginTop: 22,
    paddingVertical: 20,
    borderRadius: 20,
    backgroundColor: '$White',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  helperPanel: {
    flex: 1,
    marginHorizontal: 24,
    paddingHorizontal: 18,
    marginTop: 25,
    borderRadius: 20,
    backgroundColor: '$White',
  },
  arrowIcon: {
    color: '$BlackL',
    width: 11,
    height: 17,
  },
  level: {
    backgroundColor: '#3B387C',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 6,
    marginLeft: 10,
  },
  levelText: {
    color: '$Primary',
    fontSize: 20,
  },
  topPanel: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 32,
  },
  pollenCt: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 47,
    marginBottom: 28,
  },
  pollenText: {
    fontSize: '$FontSizeS',
    color: '#aaabb6',
  },
  aboutImg: {
    height: 28,
    width: 28,
    marginLeft: 8,
  },
  pollenNumber: {
    color: '$White',
    fontSize: 40,
  },
  pollenUtil: {
    color: '$White',
    fontSize: '$FontSizeS',
    marginRight: 20,
  },
  loading: {
    position: 'absolute',
    top: '50%',
    left: '47%',
  },
  hidden: {
    position: 'absolute',
    opacity: 0,
  },
  tipsTitle: {
    height: 24,
    width: 122,
    marginTop: 2,
  },
  tipsText: {
    color: '$Primary',
    fontSize: '$FontSizeS',
    marginLeft: 20,
  },
  tipsTextDes: {
    color: '#b19429',
    fontSize: 18,
    marginLeft: 20,
  },
  tipsBtn: {
    backgroundColor: '$Primary',
    borderRadius: 19,
    paddingVertical: 8,
    paddingHorizontal: 18,
  },
  tipsBtnText: {
    color: '#252421',
    fontSize: 22,
  },
  fansNumber: {
    color: '$White',
    fontSize: '$FontSizeL',
    fontWeight: '$Medium',
  },
  orderInfo: {
    flex: 1,
    marginHorizontal: 24,
    marginTop: 22,
    borderRadius: 20,
    backgroundColor: '$White',
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    borderColor: '#EDEDED',
    paddingHorizontal: 23,
    paddingVertical: 20,
  },
  orderPanel: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 45,
    paddingVertical: 30,
  },
  inviteBtn: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 17,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  inviteIcon: {
    width: 22,
    height: 19,
  },
  info_container: {
    marginBottom: 22,
    marginLeft: 29,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  info_bg: {
    flex: 1,
    marginLeft: 30,
    marginTop: 7,
    flexDirection: 'column',
  },
  name_level_bg: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: 300,
  },
  info_bottom_bg: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
  },
  info_bottom_left_bg: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  dao_shi_bg: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  invite_bg: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#252421',
    height: 32,
    width: 121,
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    paddingLeft: 10,
  },
  invite_text: {
    fontSize: 20,
    color: '#FED32F',
  },
  address_container: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 30,
  },
  address_bg: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },

  address_image: {
    width: 18,
    height: 22,
  },
  address_text: {
    fontSize: 20,
    color: '#1A1920',
    marginLeft: 8,
  },
};

export default StyleSheet.create(scaleStyle(style));
